x-defaults: &default-env
  restart: always
  networks:
    - backend

x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER:-airflow}:${PG_PASSWORD:-airflow}@postgres:5432/${PG_DATABASE:-airflow}
  AIRFLOW__WEBSERVER__SECRET_KEY: base64encodedFernetKeyHere
  AIRFLOW__WEBSERVER__PORT: ${AIRFLOW_PORT:-8080}
  AIRFLOW__CORE__DAG_CONCURRENCY: 16
  AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 16

services:
  postgres:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_MULTIPLE_DATABASES: 'airflow_db,mlflow_db,another_db'
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-airflow}"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  minio:
    image: minio/minio
    container_name: minio_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minio123}
    volumes:
      - minio_data:/data
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_PORT_UI:-9001}:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mlflow:
    build: ./mlflow
    env_file:
      - .env
    container_name: mlflow_tracking
    depends_on:
      - postgres
      - minio
    ports:
      - "${MLFLOW_PORT:-5000}:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY:-minio}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY:-minio123}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 20s
      retries: 3

  fastapi:
    build: ./app
    env_file:
      - .env
    volumes:
      - ./data:/data  
    container_name: fastapi_server
    depends_on:
      - mlflow
    ports:
      - "8800:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      HUGGINGFACE_TOKEN: "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"
      #OPENAI_API_KEY: ""


  airflow-webserver:
    build: 
      context: ./airflow
      dockerfile: Dockerfile
      args:
        AIRFLOW_UID: ${AIRFLOW_UID}
        AIRFLOW_GID: ${AIRFLOW_GID}
    env_file:
      - .env
    container_name: airflow_web_server
    depends_on:
      - postgres
    ports:
      - "${AIRFLOW_PORT:-8081}:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    entrypoint: /entrypoint.sh
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgres/${PG_DATABASE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
